### PR TITLE
PLAT-458  - support empty kwargs for get_object_or_none

### PR DESCRIPTION
**Pull request by gipsy86147**

### CODE REVIEW

**Comment by mflaxman** [comment]
What is the reason for this? It seems like we're making it so that if you don't pass in any kwargs on a `filter_by()` query, you get the results of an `all()` query. Seems more straightforward to have the caller use `filter_by` if they want to filter and `all()` if they want to get all.

**Comment by gipsy86147** [comment]
@mflaxman , Actually I wanted to add empty kwargs support for get_object_or_none. I'll revert the filter_by back to the original. Thanks

**Comment by gipsy86147** [comment]
@mflaxman Updated to revert the change to filter_by.

**Comment by mflaxman** [comment]
Ah. Can't they just do `.all(limit=1)` for that? Seems more straightforward what you're getting and no change needed.

**Comment by gipsy86147** [comment]
@mflaxman Then caller need to do something like below , 

```
depositories = [x async for x in cls.all(db=db, limit=1)]
if depositories:
  return depositories[0]
return None

This is what I am trying to avoid

I wanted to just do 
return await cls.get_object_or_none(db=db)

**Pull request closed without merging**
